import json

#cert_id dictionary
cert_id = {
    'CISA': 'WPC9406eafb5fa449b78108256c0575d340',
    'CISM': 'WPC12e76cfc9b824dd09b03816c79b29470',
    'SSCP': 'WPC20462535577e4312be8de4a7f47b1626',
    'CISSP': 'WPC1936500573674480abd37a4202cd66d4',
    'CCSP': 'WPC1305a63b853849f790d91799712e4b96',
    'CISSP-2024':'WPC50bbe8d93e7d466bb3bef2070fd1cb0d',
}
# cert_domain_id dictionary
cert_domain_id = {
    'CISA_DOMAIN' : {
        "1": "WCD8b61e90a9d5b498fac789f6406fced05", #"INFORMATION SYSTEMS AUDITING PROCESS"
        "2": "WCD36cbbcfd89fa49d592092915d874f7f2", #"GOVERNANCE & MANAGEMENT OF IT",
        "3": "WCDa0680ae0c0a24f3493f4ac310ea6b3d4", #"INFORMATION SYSTEMS ACQUISITION, DEVELOPMENT & IMPLEMENTATION",
        "4": "WCDf3ffccafb8ca4bb7831f797cf21eff33", #"INFORMATION SYSTEMS OPERATIONS & BUSINESS RESILIENCE",
        "5": "WCDda4401b6eaba40d1b4380376b74928e4"  #"PROTECTION OF INFORMATION ASSETS"
    },
    'CISM_DOMAIN' : {
        "1": "WCDb75922760a6647e7bfd9bc22ec05f1b6", #"Information Security Governance",
        "2": "WCDf89bca4fe870433382579c53927ff7a4", #"Information Security Risk Management",
        "3": "WCD9c7a301bf316460d916852797ce7fef4", #"Information Security Program",
        "4": "WCD9106318d1794405ba6cba802fcb75e9f", #"Incident Management",
    },
    'SSCP_DOMAIN' : {
        "1": "WCDc856e9462a4b449ba100fc97189a505c", #"Security Operations and Administration",
        "2": "WCDdac4c3725dea46849642c5254050b23b", #"Access Controls",
        "3": "WCD3e9b1bad98a847eab64f0d39a81288e6", #"Risk Identification, Monitoring and Analysis",
        "4": "WCD9f99339fa50a46b0bd94244473f36896", #"Incident Response and Recovery",
        "5": "WCD1c4f0e9642cb4e279f73b87c7cc5cc1b", #"Cryptography",
        "6": "WCD362c0937d44949eba8f65a137dbc33e9", #"Network and Communications Security",
        "7": "WCDf9393685938b43c6a4987c2682c98940", #"Systems and Application Security"
    },
    'CISSP_DOMAIN' : {
     "1": "WCD6a93ebb95035456095362f6a4a57d122", #"Security and Risk Management",
     "2": "WCD60a9617d0fb24266943bb9f37271b574", #"Asset Security",
     "3": "WCD998ee393ac064838a7d0bd3ce68cd0f6", #"Security Architecture and Engineering",
     "4": "WCD4d570a7718f24f36a762b2e62f9658e3", #"Communication and Network Security",
     "5": "WCD55b4839d00c14e41b273e910efd909e1", #"Identity and Access Management (IAM)",
     "6": "WCD5c64ab29439b4f2c997f37b6371a913c", #"Security Assessment and Testing",
     "7": "WCDe6c9c7c44b2849998bead50e44fc17a8", #"Security Operations",
     "8": "WCD37414532e0cd45a28937f96657274f88", #"Software Development Security"
},
    'CCSP_DOMAIN' : {
    "1": "WCDd0d70262f32b44fc8b97decf6405634e", #"Cloud Concepts, Architecture and Design",
    "2": "WCDdc44608e780943969e74d6d825cbd27d", #"Cloud Data Security",
    "3": "WCD34e95b7c1ce1439995aa03a41533b628", #"Cloud Platform and Infrastructure Security",
    "4": "WCD72361a2467f744d6ac8e5215ec33c609", #"Cloud Application Security",
    "5": "WCD36fe5f884dab42ecb078e5583272b0a5", #"Cloud Security Operations",
    "6": "WCDc1b5942e13374f2eb114b7496a2175b7", #"Legal, Risk and Compliance"
},
    'CISSP-2024_DOMAIN' : {
    "1": "WCD0b1779b4e3084a6882a776b853c389c4", #"Security and Risk Management",
    "2": "WCD5b435d240e4a401cb07a87a508623340", #"Asset Security",
    "3": "WCDbbeb56d29639468f8fa1fd34c0eb3b8a", #"Security Architecture and Engineering",
    "4": "WCDfc1cab2be5024149814aa092a2ae4fe0", #"Communication and Network Security",
    "5": "WCD4e5e4f5088864312a0b1051f60a1537a", #"Identity and Access Management (IAM)",
    "6": "WCD2cc41bab5fb1472f91358cadf94c796b", #"Security Assessment and Testing",
    "7": "WCD0559ebed11a54803bea22ab0103df37d", #"Security Operations",
    "8": "WCD0279a9d74541432ba5392b8375047470", #"Software Development Security"
},
}
topic = {    
'CISA'  : {
            "1A1": "IS Audit Standards, Guidelines, and Codes of Ethics",
            "1A2": "Business Processes",
            "1A3": "Types of Controls",
            "1A4": "Risk-Based Audit Planning",
            "1A5": "Types of Audits and Assessments",
            "1B1": "Audit Project Management",
            "1B2": "Sampling Methodology",
            "1B3": "Audit Evidence Collection Techniques",
            "1B4": "Data Analytics",
            "1B5": "Reporting and Communication Techniques",
            "1B6": "Quality Assurance and Improvement of the Audit Process",
            "2A1": "IT Governance and IT Strategy",
            "2A2": "IT-Related Frameworks",
            "2A3": "IT Standards, Policies, and Procedures",
            "2A4": "Organizational Structure",
            "2A5": "Enterprise Architecture",
            "2A6": "Enterprise Risk Management",
            "2A7": "Maturity Models",
            "2A8": "Laws, Regulations, and Industry Standards affecting the Organization",
            "2B1": "IT Resource Management",
            "2B2": "IT Service Provider Acquisition and Management",
            "2B3": "IT Performance Monitoring and Reporting",
            "2B4": "Quality Assurance and Quality Management of IT",
            "3A1": "Project Governance and Management",
            "3A2": "Business Case and Feasibility Analysis",
            "3A3": "System Development Methodologies",
            "3A4": "Control Identification and Design",
            "3B1": "Testing Methodologies",
            "3B2": "Configuration and Release Management",
            "3B3": "System Migration, Infrastructure Deployment and Data Conversion",
            "3B4": "Post-implementation Review",
            "4A1": "Common Technology Components",
            "4A2": "IT Asset Management",
            "4A3": "Job Scheduling and Production Process Automation",
            "4A4": "System Interfaces",
            "4A5": "End-User Computing",
            "4A6": "Data Governance",
            "4A7": "Systems Performance Management",
            "4A8": "Problem and Incident Management",
            "4A9": "Change, Configuration, Release, and Patch Management",
            "4A10": "IT Service Level Management",
            "4A11": "Database Management",
            "4B1": "Business Impact Analysis (BIA)",
            "4B2": "System Resiliency",
            "4B3": "Data Backup, Storage, and Restoration",
            "4B4": "Business Continuity Plan (BCP)",
            "4B5": "Disaster Recovery Plans (DRP)",
            "5A1": "Information Asset Security Frameworks, Standards, and Guidelines",
            "5A2": "Privacy Principles",
            "5A3": "Physical Access and Environmental Controls",
            "5A4": "Identity and Access Management",
            "5A5": "Network and End-Point Security",
            "5A6": "Data Classification",
            "5A7": "Data Encryption and Encryption-Related Techniques",
            "5A8": "Public Key Infrastructure (PKI)",
            "5A9": "Web-Based Communication Techniques",
            "5A10": "Virtualized Environments",
            "5A11": "Mobile, Wireless, and Internet-of-Things (IoT) Devices",
            "5B1": "Security Awareness Training and Programs",
            "5B2": "Information System Attack Methods and Techniques",
            "5B3": "Security Testing Tools and Techniques",
            "5B4": "Security Monitoring Tools and Techniques",
            "5B5": "Incident Response Management",
            "5B6": "Evidence Collection and Forensics"
},

'CISM' : {                                  
    "1A1":  "Organizational Culture",                          
    "1A2": "Legal, Regulatory, and Contractual Requirements",
    "1A3": "Organizational Structures, Roles, and Responsibilities",
    "1B1": "Information Security Strategy Development",
    "1B2": "Information Governance Frameworks and Standards",
    "1B3": "Strategic Planning",
    "2A1": "Emerging Risk and Threat Landscape",
    "2A2": "Vulnerability and Control Deficiency Analysis",
    "2A3": "Risk Assessment and Analysis",
    "2B1": "Risk Treatment / Risk Response Options",
    "2B2": "Risk and Control Ownership",
    "2B3": "Risk Monitoring and Reporting",
    "3A1": "Information Security Program Resources",
    "3A2": "Information Asset Identification and Classification",
    "3A3": "Industry Standards and Frameworks for Information Security",
    "3A4": "Information Security Policies, Procedures, and Guidelines",
    "3A5": "Information Security Program Metrics",
    "3B1": "Information Security Control Design and Selection",
    "3B2": "Information Security Control Implementation and Integrations",
    "3B3": "Information Security Control Testing and Evaluation",
    "3B4": "Information Security Awareness and Training",
    "3B5": "Management of External Services",
    "3B6": "Information Security Program Communications and Reporting",
    "4A1": "Incident Response Plan",
    "4A2": "Business Impact Analysis (BIA)",
    "4A3": "Business Continuity Plan (BCP)",
    "4A4": "Disaster Recovery Plan (DRP)",
    "4A5": "Incident Classification/Categorization",
    "4A6": "Incident Management Training, Testing, and Evaluation",
    "4B1": "Incident Management Tools and Techniques",
    "4B2": "Incident Investigation and Evaluation",
    "4B3": "Incident Containment Methods",
    "4B4": "Incident Response Communications",
    "4B5": "Incident Eradication and Recovery",
    "4B6": "Post-incident Review Practices"
},

'SSCP' : {
        "1.1": "Comply with codes of ethics",
        "1.2": "Understand security concepts",
        "1.3": "Identify and implement security controls",
        "1.4": "Document and maintain functional security controls",
        "1.5": "Participate in asset management lifecycle",
        "1.6": "Participate in change management lifecycle",
        "1.7": "Participate in implementing security awareness and training",
        "1.8": "Collaborate with physical security operations",
        "2.1": "Implement and maintain authentication methods",
        "2.2": "Support internetwork trust architectures",
        "2.3": "Participate in the identity management lifecycle",
        "2.4": "Understand and apply access controls",
        "3.1": "Understand the risk management process",
        "3.2": "Understand legal and regulatory concerns",
        "3.3": "Participate in security assessment and vulnerability management activities",
        "3.4": "Operate and monitor security platforms",
        "3.5": "Analyze monitoring results",
        "4.1": "Support incident lifecycle, International Organization for Standardization",
        "4.2": "Understand and support forensic investigations",
        "4.3": "Understand and support business continuity plan (BCP) and disaster recovery plan (DRP) activities",
        "5.1": "Understand reasons and requirements for cryptography",
        "5.2": "Apply cryptography concepts",
        "5.3": "Understand and implement secure protocols",
        "5.4": "Understand and support public key infrastructure (PKI) systems",
        "6.1": "Understand and apply fundamental concepts of networking",
        "6.2": "Understand network attacks, man-in-the-middle, Domain Name System and countermeasures",
        "6.3": "Manage network access controls",
        "6.4": "Manage network security",
        "6.5": "Operate and configure network-based security devices",
        "6.6": "Secure wireless communications",
        "7.1": "Identify and analyze malicious code and activity",
        "7.2": "Implement and operate endpoint device security",
        "7.3": "Administer Mobile Device Management",
        "7.4": "Understand and configure cloud security",
        "7.5": "Operate and maintain secure virtual environments"
    },

'CISSP' : {
    "1.1": "Understand, adhere to, and promote professional ethics (ISC)² Code of Professional Ethics, Organizational code of ethics",
    "1.2": "Understand and apply security concepts Confidentiality, integrity, and availability, authenticity and nonrepudiation",
    "1.3": "Evaluate and apply security governance principles Alignment of the security function to business strategy ",
    "1.4": "Determine compliance and other requirements Contractual, legal, industry standards, and regulatory requirements, Privacy requirements",
    "1.5": "Understand legal and regulatory issues that pertain to information security in a holistic context Cybercrimes and data breaches",
    "1.6": "Understand requirements for investigation types",
    "1.7": "Develop, document, and implement security policy, standards, procedures, and guidelines",
    "1.8": "Identify, analyze, and prioritize Business Continuity (BC) requirements Business Impact Analysis (BIA), Develop and document the scope and the plan",
    "1.9": "Contribute to and enforce personnel security policies and procedures Candidate screening and hiring",
    "1.10": "Understand and apply risk management concepts Identify threats and vulnerabilities, Risk assessment/analysis",
    "1.11": "Understand and apply threat modeling concepts and methodologies",
    "1.12": "Apply Supply Chain Risk Management (SCRM) concepts Risks associated with hardware, software, and services",
    "1.13": "Establish and maintain a security awareness, education, and training program Methods and techniques to present awareness and training",
    "2.1": "Identify and classify information and assets Data classification, Asset Classification",
    "2.2": "Establish information and asset handling requirements",
    "2.3": "Provision resources securely Information and asset ownership, Asset inventory, Asset management",
    "2.4": "Manage data lifecycle Data roles, Data collection, Data location, Data maintenance, Data retention, Data remanence, Data destruction",
    "2.5": "Ensure appropriate asset retention",
    "2.6": "Determine data security controls and compliance requirements Data states, Scoping and tailoring, Standards selection, Data protection methods",
    "3.1": "Research, implement and manage engineering processes using secure design principles Threat modeling, Least privilege,  ",
    "3.2": "Understand the fundamental concepts of security models",
    "3.3": "Select controls based upon systems security requirements",
    "3.4": "Understand security capabilities of Information Systems (IS)",
    "3.5": "Assess and mitigate the vulnerabilities of security architectures, designs, and solution elements Client-based systems, ",
    "3.6": "Select and determine cryptographic solutions Cryptographic life cycle, Cryptographic methods, Public Key Infrastructure (PKI) ",
    "3.7": "Understand methods of cryptanalytic attacks Brute force, Ciphertext only, Known plaintext, Frequency analysis, Chosen ciphertext ",
    "3.8": "Apply security principles to site and facility design",
    "3.9": "Design site and facility security controls Wiring closets/intermediate distribution facilities, Server rooms/data centers ",
    "4.1": "Assess and implement secure design principles in network architectures: Open System Interconnection (OSI) ",
    "4.2": "Secure network components: Operation of hardware ",
    "4.3": "Implement secure communication channels according to design",
    "5.1": "Control physical and logical access to assets: Information, Systems, Devices, Facilities, Applications",
    "5.2": "Manage identification and authentication of people, devices, and services: Identity Management (IdM) implementation, Single/Multi-Factor Authentication (MFA)",
    "5.3": "Federated identity with a third-party service: On-premise, Cloud, Hybrid",
    "5.4": "Implement and manage authorization mechanisms: Role Based Access Control (RBAC), Rule based access control, Mandatory Access Control (MAC), Discretionary Access Control (DAC)",
    "5.5": "Manage the identity and access provisioning lifecycle: Account access review ",
    "5.6": "Implement authentication systems: OpenID Connect (OIDC)/Open Authorization (Oauth), Security Assertion Markup Language (SAML), Kerberos ",
    "6.1": "Design and validate assessment, test, and audit strategies: Internal, External, Third-party",
    "6.2": "Conduct security control testing: Vulnerability assessment, Penetration testing, Log reviews, Synthetic transactions, Code review and testing",
    "6.3": "Collect security process data ",
    "6.4": "Analyze test output and generate report: Remediation, Exception handling, Ethical disclosure",
    "6.5": "Conduct or facilitate security audits: Internal, External, Third-party",
    "7.1": "Understand and comply with investigations: Evidence collection and handling, Reporting and documentation, Investigative techniques, Digital forensics tools, tactics, and procedures, Artifacts ",
    "7.2": "Conduct logging and monitoring activities: Intrusion detection and prevention",
    "7.3": "Perform Configuration Management (CM) ",
    "7.4": "Apply foundational security operations concepts: Need-to-know/least privilege, Separation of Duties (SoD) ",
    "7.5": "Apply resource protection: Media management, Media protection techniques",
    "7.6": "Conduct incident management: Detection, Response, Mitigation, Reporting, Recovery, Remediation, Lessons learned",
    "7.7": "Operate and maintain detective and preventative measures: Firewalls ",
    "7.8": "Implement and support patch and vulnerability management",
    "7.9": "Understand and participate in change management processes",
    "7.10": "Implement recovery strategies: Backup storage strategies, Recovery site strategies, Multiple processing sites, System resilience",
    "7.11": "Implement Disaster Recovery (DR) processes: Response, Personnel, Communications, Assessment, Restoration, Training and awareness, Lessons learned",
    "7.12": "Test Disaster Recovery Plans (DRP): Read-through/tabletop, Walkthrough, Simulation, Parallel, Full interruption",
    "7.13": "Participate in Business Continuity (BC) planning and exercises",
    "7.14": "Implement and manage physical security: Perimeter security controls, Internal security controls",
    "7.15": "Address personnel safety and security concerns: Travel, Security training and awareness, Emergency management, Duress",
    "8.1": "Understand and integrate security in the Software Development Life Cycle (SDLC): Development methodologies ",
    "8.2": "Identify and apply security controls in software development ecosystems: Programming languages, Libraries ",
    "8.3": "Assess the effectiveness of software security: Auditing and logging of changes, Risk analysis and mitigation",
    "8.4": "Assess security impact of acquired software: Commercial-off-the-shelf (COTS), Open source, Third-party, Managed services ",
    "8.5": "Define and apply secure coding guidelines and standards: Security weaknesses and vulnerabilities at the source-code level",
},

'CCSP' : {
    "1.1": "Understand cloud computing concepts Cloud computing definitions, Cloud computing roles and responsibilities ",
    "1.2": "Describe cloud reference architecture Cloud computing activities, Cloud service capabilities (application capability types",
    "1.3": "Understand security concepts relevant to cloud computing Cryptography and key management, Identity and access control (user access, privilege access, service access), Data and media sanitization  ",
    "1.4": "Understand design principles of secure cloud computing Cloud secure data lifecycle, Cloud-based business continuity (BC) and disaster recovery (DR) plan, Business impact analysis ",
    "1.5": "Evaluate cloud service providers Verification against criteria (International Organization for Standardization/International Electrotechnical Commission ",
    "2.1": "Describe cloud data concepts Cloud data life cycle phases, Data dispersion, Data flows",
    "2.2": "Design and implement cloud data storage architectures Storage types (long-term, ephemeral, raw storage), Threats to storage types",
    "2.3": "Design and apply data security technologies and strategies Encryption and key management, Hashing, Data obfuscation ",
    "2.4": "Implement data discovery Structured data, Unstructured data, Semi-structured data, Data location",
    "2.5": "Implement data classification Data classification policies, Data mapping, Data labeling",
    "2.6": "Design and implement Information Rights Management (IRM) Objectives (data rights, provisioning, access models), Appropriate tools (issuing and revocation of certificates)",
    "2.7": "Plan and implement data retention, deletion, and archiving policies Data retention policies, Data deletion procedures and mechanisms, Data archiving procedures and mechanisms, Legal hold",
    "2.8": "Design and implement auditability, traceability, and accountability of data events Definition of event sources and requirement of event attributes ",
    "3.1": "Comprehend cloud infrastructure components Physical environment, Network and communications, Compute, Virtualization, Storage, Management plane",
    "3.2": "Design a secure data center Logical design (tenant partitioning, access control), Physical design (location, buy or build), Environmental design ",
    "3.3": "Analyze risks associated with cloud infrastructure Risk assessment (identification, analysis), Cloud vulnerabilities, threats and attacks, Risk mitigation strategies",
    "3.4": "Design and plan security controls Physical and environmental protection (on-premises), System, storage and communication protection",
    "3.5": "Plan Disaster Recovery (DR) and Business Continuity (BC) Business continuity (BC) / disaster recovery (DR) strategy, Business requirements ",
    "4.1": "Advocate training and awareness for application security Cloud development basics, Common pitfalls, Common cloud vulnerabilities ",
    "4.2": "Describe the Secure Software Development Life Cycle (SDLC) process Business requirements, Phases and methodologies ",
    "4.3": "Apply the Secure Software Development Life Cycle (SDLC) Cloud-specific risks, Threat modeling ",
    "4.4": "Apply cloud software assurance and validation Functional and non-functional testing, Security testing methodologies ",
    "4.5": "Use verified secure software Securing application programming interfaces (API), Supply-chain management ",
    "4.6": "Comprehend the specifics of cloud application architecture Supplemental security components ",
    "4.7": "Design appropriate Identity and Access Management (IAM) solutions Federated identity, Identity providers (IdP), Single sign-on (SSO)",
    "5.1": "Build and implement physical and logical infrastructure for cloud environment Hardware specific security configuration requirements",
    "5.2": "Operate and maintain physical and logical infrastructure for cloud environment Access controls for local and remote access ",
    "5.3": "Implement operational controls and standards",
    "5.4": "Support digital forensics Forensic data collection methodologies, Evidence management, Collect, acquire, and preserve digital evidence",
    "5.5": "Manage communication with relevant parties Vendors, Customers, Partners, Regulators, Other stakeholders",
    "5.6": "Manage security operations Forensic data collection methodologies, Evidence management, Collect, acquire ",
    "6.1": "Articulate legal requirements and unique risks within the cloud environment Conflicting international legislation, Evaluation of legal risks specific to cloud computing, Legal framework and guidelines, eDiscovery ",
    "6.3": "Understand audit process, methodologies",
    "6.2": "Understand privacy issues",
    "6.4": "Understand implications of cloud to enterprise risk management Assess providers risk management programs",
    "6.5": "Understand outsourcing and cloud contract design Business requirements (service-level agreement (SLA)"
},
'CISSP-2024' : {
    "1.1": "Understand, adhere to, and promote professional ethics (ISC)² Code of Professional Ethics, Organizational code of ethics",
    "1.2": "Understand and apply security concepts Confidentiality, integrity, and availability, authenticity and nonrepudiation",
    "1.3": "Evaluate and apply security governance principles Alignment of the security function to business strategy ",
    "1.4": "Determine compliance and other requirements Contractual, legal, industry standards, and regulatory requirements, Privacy requirements",
    "1.5": "Understand legal and regulatory issues that pertain to information security in a holistic context Cybercrimes and data breaches",
    "1.6": "Understand requirements for investigation types",
    "1.7": "Develop, document, and implement security policy, standards, procedures, and guidelines",
    "1.8": "Identify, analyze, and prioritize Business Continuity (BC) requirements Business Impact Analysis (BIA), Develop and document the scope and the plan",
    "1.9": "Contribute to and enforce personnel security policies and procedures Candidate screening and hiring",
    "1.10": "Understand and apply risk management concepts Identify threats and vulnerabilities, Risk assessment/analysis",
    "1.11": "Understand and apply threat modeling concepts and methodologies",
    "1.12": "Apply Supply Chain Risk Management (SCRM) concepts Risks associated with hardware, software, and services",
    "2.1": "Identify and classify information and assets Data classification, Asset Classification",
    "2.2": "Establish information and asset handling requirements",
    "2.3": "Provision resources securely Information and asset ownership, Asset inventory, Asset management",
    "2.4": "Manage data lifecycle Data roles, Data collection, Data location, Data maintenance, Data retention, Data remanence, Data destruction",
    "2.5": "Ensure appropriate asset retention",
    "2.6": "Determine data security controls and compliance requirements Data states, Scoping and tailoring, Standards selection, Data protection methods",
    "3.1": "Research, implement and manage engineering processes using secure design principles Threat modeling, Least privilege,  ",
    "3.2": "Understand the fundamental concepts of security models",
    "3.3": "Select controls based upon systems security requirements",
    "3.4": "Understand security capabilities of Information Systems (IS)",
    "3.5": "Assess and mitigate the vulnerabilities of security architectures, designs, and solution elements Client-based systems, ",
    "3.6": "Select and determine cryptographic solutions Cryptographic life cycle, Cryptographic methods, Public Key Infrastructure (PKI) ",
    "3.7": "Understand methods of cryptanalytic attacks Brute force, Ciphertext only, Known plaintext, Frequency analysis, Chosen ciphertext ",
    "3.8": "Apply security principles to site and facility design",
    "3.9": "Design site and facility security controls Wiring closets/intermediate distribution facilities, Server rooms/data centers ",
    "4.1": "Assess and implement secure design principles in network architectures: Open System Interconnection (OSI) ",
    "4.2": "Secure network components: Operation of hardware ",
    "4.3": "Implement secure communication channels according to design",
    "5.1": "Control physical and logical access to assets: Information, Systems, Devices, Facilities, Applications",
    "5.2": "Manage identification and authentication of people, devices, and services: Identity Management (IdM) implementation, Single/Multi-Factor Authentication (MFA)",
    "5.3": "Federated identity with a third-party service: On-premise, Cloud, Hybrid",
    "5.4": "Implement and manage authorization mechanisms: Role Based Access Control (RBAC), Rule based access control, Mandatory Access Control (MAC), Discretionary Access Control (DAC)",
    "5.5": "Manage the identity and access provisioning lifecycle: Account access review ",
    "5.6": "Implement authentication systems: OpenID Connect (OIDC)/Open Authorization (Oauth), Security Assertion Markup Language (SAML), Kerberos ",
    "6.1": "Design and validate assessment, test, and audit strategies: Internal, External, Third-party",
    "6.2": "Conduct security control testing: Vulnerability assessment, Penetration testing, Log reviews, Synthetic transactions, Code review and testing",
    "6.3": "Collect security process data ",
    "6.4": "Analyze test output and generate report: Remediation, Exception handling, Ethical disclosure",
    "6.5": "Conduct or facilitate security audits: Internal, External, Third-party",
    "7.1": "Understand and comply with investigations: Evidence collection and handling, Reporting and documentation, Investigative techniques, Digital forensics tools, tactics, and procedures, Artifacts ",
    "7.2": "Conduct logging and monitoring activities: Intrusion detection and prevention",
    "7.3": "Perform Configuration Management (CM) ",
    "7.4": "Apply foundational security operations concepts: Need-to-know/least privilege, Separation of Duties (SoD) ",
    "7.5": "Apply resource protection: Media management, Media protection techniques",
    "7.6": "Conduct incident management: Detection, Response, Mitigation, Reporting, Recovery, Remediation, Lessons learned",
    "7.7": "Operate and maintain detective and preventative measures: Firewalls ",
    "7.8": "Implement and support patch and vulnerability management",
    "7.9": "Understand and participate in change management processes",
    "7.10": "Implement recovery strategies: Backup storage strategies, Recovery site strategies, Multiple processing sites, System resilience",
    "7.11": "Implement Disaster Recovery (DR) processes: Response, Personnel, Communications, Assessment, Restoration, Training and awareness, Lessons learned",
    "7.12": "Test Disaster Recovery Plans (DRP): Read-through/tabletop, Walkthrough, Simulation, Parallel, Full interruption",
    "7.13": "Participate in Business Continuity (BC) planning and exercises",
    "7.14": "Implement and manage physical security: Perimeter security controls, Internal security controls",
    "7.15": "Address personnel safety and security concerns: Travel, Security training and awareness, Emergency management, Duress",
    "8.1": "Understand and integrate security in the Software Development Life Cycle (SDLC): Development methodologies ",
    "8.2": "Identify and apply security controls in software development ecosystems: Programming languages, Libraries ",
    "8.3": "Assess the effectiveness of software security: Auditing and logging of changes, Risk analysis and mitigation",
    "8.4": "Assess security impact of acquired software: Commercial-off-the-shelf (COTS), Open source, Third-party, Managed services ",
    "8.5": "Define and apply secure coding guidelines and standards: Security weaknesses and vulnerabilities at the source-code level",
}
}

def certificate_mapping(domain_name, topic_name):
    print(f'Logging domain name:{domain_name}, topic_name:{topic_name}\n')

    domain_key = str(domain_name).upper() + '_DOMAIN'
    print(f'Logging domain_key:{domain_key}')
    
    # domain_value = domain.get(domain_key).get(topic_name[0])
    # print(f'Logging domain_value:{domain_value}')
    
    topic_key = str(domain_name).upper()
    print(f'Logging topic_key:{topic_key}')
    
    # topic_value = topic.get(topic_key).get(topic_name)
    # print(f'Logging topic value:{topic_value}')


    domain_mapping = {"cert_assocs": [
        {
            "cert_id": cert_id.get(domain_name),
            "cert_domain_id": cert_domain_id.get(domain_key).get(topic_name[0]),
            "topic": topic.get(topic_key).get(topic_name)
        }
    ]
    }

    return domain_mapping